# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\PyProjects\ximalaya_qt\uiFile\WavWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WavWindow(object):
    def setupUi(self, WavWindow):
        WavWindow.setObjectName("WavWindow")
        WavWindow.resize(1121, 602)
        self.centralwidget = QtWidgets.QWidget(WavWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_songID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_songID.setGeometry(QtCore.QRect(70, 50, 161, 21))
        self.lineEdit_songID.setText("")
        self.lineEdit_songID.setObjectName("lineEdit_songID")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 51, 16))
        self.label.setObjectName("label")
        self.pushButton_mini = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mini.setGeometry(QtCore.QRect(1030, 0, 31, 28))
        self.pushButton_mini.setText("")
        self.pushButton_mini.setObjectName("pushButton_mini")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(1080, 0, 31, 28))
        self.pushButton_close.setText("")
        self.pushButton_close.setShortcut("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 50, 41, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 50, 61, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_songPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_songPath.setGeometry(QtCore.QRect(310, 50, 161, 21))
        self.lineEdit_songPath.setObjectName("lineEdit_songPath")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 50, 51, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(790, 50, 61, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_listPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_listPath.setGeometry(QtCore.QRect(860, 50, 161, 21))
        self.lineEdit_listPath.setObjectName("lineEdit_listPath")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1030, 50, 41, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_listID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_listID.setGeometry(QtCore.QRect(620, 50, 161, 21))
        self.lineEdit_listID.setText("")
        self.lineEdit_listID.setObjectName("lineEdit_listID")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(510, 110, 61, 16))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(530, 20, 21, 71))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 90, 1041, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.Text_Output = QtWidgets.QTextEdit(self.centralwidget)
        self.Text_Output.setGeometry(QtCore.QRect(190, 150, 701, 361))
        self.Text_Output.setObjectName("Text_Output")
        WavWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WavWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        WavWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WavWindow)
        self.statusbar.setObjectName("statusbar")
        WavWindow.setStatusBar(self.statusbar)
        self.action_Mat = QtWidgets.QAction(WavWindow)
        self.action_Mat.setObjectName("action_Mat")
        self.action_Wav = QtWidgets.QAction(WavWindow)
        self.action_Wav.setObjectName("action_Wav")
        self.menu.addAction(self.action_Mat)
        self.menu.addAction(self.action_Wav)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(WavWindow)
        QtCore.QMetaObject.connectSlotsByName(WavWindow)

    def retranslateUi(self, WavWindow):
        _translate = QtCore.QCoreApplication.translate
        WavWindow.setWindowTitle(_translate("WavWindow", "MainWindow"))
        self.label.setText(_translate("WavWindow", "歌曲ID"))
        self.pushButton.setText(_translate("WavWindow", "返回"))
        self.pushButton_2.setText(_translate("WavWindow", "下载"))
        self.label_2.setText(_translate("WavWindow", "保存路径"))
        self.lineEdit_songPath.setText(_translate("WavWindow", "./"))
        self.label_3.setText(_translate("WavWindow", "歌单ID"))
        self.label_4.setText(_translate("WavWindow", "保存路径"))
        self.lineEdit_listPath.setText(_translate("WavWindow", "./"))
        self.pushButton_3.setText(_translate("WavWindow", "下载"))
        self.label_5.setText(_translate("WavWindow", "下载结果"))
        self.menu.setTitle(_translate("WavWindow", "功能"))
        self.action_Mat.setText(_translate("WavWindow", "MatCalculate"))
        self.action_Wav.setText(_translate("WavWindow", "WavView"))

