# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\PyProjects\ximalaya_qt\uiFile\WYYWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WavWindow(object):
    def setupUi(self, WavWindow):
        WavWindow.setObjectName("WavWindow")
        WavWindow.resize(1121, 602)
        self.centralwidget = QtWidgets.QWidget(WavWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_songID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_songID.setGeometry(QtCore.QRect(60, 90, 161, 21))
        self.lineEdit_songID.setObjectName("lineEdit_songID")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 90, 51, 16))
        self.label.setObjectName("label")
        self.pushButton_mini = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mini.setGeometry(QtCore.QRect(1030, 10, 31, 28))
        self.pushButton_mini.setText("")
        self.pushButton_mini.setObjectName("pushButton_mini")
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(1080, 10, 31, 28))
        self.pushButton_close.setText("")
        self.pushButton_close.setShortcut("")
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_back = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_back.setGeometry(QtCore.QRect(0, 10, 93, 28))
        self.pushButton_back.setObjectName("pushButton_back")
        self.pushButton_downloadsong = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_downloadsong.setGeometry(QtCore.QRect(450, 90, 71, 21))
        self.pushButton_downloadsong.setObjectName("pushButton_downloadsong")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 90, 61, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_songPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_songPath.setGeometry(QtCore.QRect(300, 90, 81, 21))
        self.lineEdit_songPath.setObjectName("lineEdit_songPath")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 90, 51, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(790, 90, 61, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_listPath = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_listPath.setGeometry(QtCore.QRect(860, 90, 81, 21))
        self.lineEdit_listPath.setObjectName("lineEdit_listPath")
        self.pushButton_listDownload = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_listDownload.setGeometry(QtCore.QRect(1010, 90, 71, 21))
        self.pushButton_listDownload.setObjectName("pushButton_listDownload")
        self.lineEdit_listID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_listID.setGeometry(QtCore.QRect(620, 90, 161, 21))
        self.lineEdit_listID.setObjectName("lineEdit_listID")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(510, 150, 61, 16))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(530, 40, 21, 91))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 120, 1111, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton_openPathsong = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openPathsong.setGeometry(QtCore.QRect(390, 90, 31, 21))
        self.pushButton_openPathsong.setObjectName("pushButton_openPathsong")
        self.pushButton_openPathList = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_openPathList.setGeometry(QtCore.QRect(950, 90, 31, 21))
        self.pushButton_openPathList.setObjectName("pushButton_openPathList")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(150, 180, 781, 361))
        self.textBrowser.setObjectName("textBrowser")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 30, 1111, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(210, 40, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(770, 40, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 70, 521, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(560, 70, 521, 16))
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        WavWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WavWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 26))
        self.menubar.setObjectName("menubar")
        WavWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WavWindow)
        self.statusbar.setObjectName("statusbar")
        WavWindow.setStatusBar(self.statusbar)
        self.action_Mat = QtWidgets.QAction(WavWindow)
        self.action_Mat.setObjectName("action_Mat")
        self.action_Wav = QtWidgets.QAction(WavWindow)
        self.action_Wav.setObjectName("action_Wav")

        self.retranslateUi(WavWindow)
        QtCore.QMetaObject.connectSlotsByName(WavWindow)

    def retranslateUi(self, WavWindow):
        _translate = QtCore.QCoreApplication.translate
        WavWindow.setWindowTitle(_translate("WavWindow", "MainWindow"))
        self.lineEdit_songID.setText(_translate("WavWindow", "1426844352"))
        self.label.setText(_translate("WavWindow", "歌曲ID"))
        self.pushButton_back.setText(_translate("WavWindow", "返回"))
        self.pushButton_downloadsong.setText(_translate("WavWindow", "单曲下载"))
        self.label_2.setText(_translate("WavWindow", "保存路径"))
        self.lineEdit_songPath.setText(_translate("WavWindow", "./"))
        self.label_3.setText(_translate("WavWindow", "歌单ID"))
        self.label_4.setText(_translate("WavWindow", "保存路径"))
        self.lineEdit_listPath.setText(_translate("WavWindow", "./"))
        self.pushButton_listDownload.setText(_translate("WavWindow", "歌单下载"))
        self.lineEdit_listID.setText(_translate("WavWindow", "3085577764"))
        self.label_5.setText(_translate("WavWindow", "下载结果"))
        self.pushButton_openPathsong.setText(_translate("WavWindow", "..."))
        self.pushButton_openPathList.setText(_translate("WavWindow", "..."))
        self.textBrowser.setHtml(_translate("WavWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">去网易云查找歌曲或者歌单然后填写上面的空缺</span></p></body></html>"))
        self.label_6.setText(_translate("WavWindow", "单曲下载"))
        self.label_7.setText(_translate("WavWindow", "歌单下载"))
        self.label_8.setText(_translate("WavWindow", "例如：https://music.163.com/#/song?id=1426844352"))
        self.label_9.setText(_translate("WavWindow", "例如：https://music.163.com/#/playlist?id=3085577764 "))
        self.action_Mat.setText(_translate("WavWindow", "MatCalculate"))
        self.action_Wav.setText(_translate("WavWindow", "WavView"))

